### ISSUE TITLE
CARGO_TARGET_DIR not set

### ISSUE THREAD

**Issue by Vrixyz** [mrk-its/bevy_webgl2_app_template#1]
From my understanding, that line is supposed to set a default value for environment variable `CARGO_TARGET_DIR` :

https://github.com/mrk-its/bevy_webgl2_app_template/blob/master/Makefile.toml#L5
`CARGO_TARGET_DIR = {source = "${CARGO_TARGET_DIR}", default_value = "target"}`

But it seems not to work, as shows: **NO**  `CARGO_TARGET_DIR`
<img width="691" alt="Capture d’écran 2020-11-29 à 09 32 37" src="https://user-images.githubusercontent.com/2290685/100537104-d8f44d00-3225-11eb-9830-1f262ba02d4f.png">

If I modify that line though, `show-env` shows correctly the environment variable `CARGO_TARGET_DIR`:
<img width="737" alt="Capture d’écran 2020-11-29 à 09 34 07" src="https://user-images.githubusercontent.com/2290685/100537140-3ab4b700-3226-11eb-99bb-c9458bcef262.png">

Building works correctly with above modification.

But without, cargo-make fails:
<img width="576" alt="Capture d’écran 2020-11-29 à 09 36 24" src="https://user-images.githubusercontent.com/2290685/100537181-89625100-3226-11eb-809d-41ea874e4067.png">

It might be a bug within cargo-make, I'm not sure 🤷

**Comment by mrk-its** [comment]
@Vrixyz good catch, fixed!
