### ISSUE TITLE
Should Cargo.lock be in .gitignore?

### ISSUE THREAD

**Issue by rparrett** [mrk-its/bevy_webgl2_app_template#11]
Or should the `bevy_webgl2` dep be bumped to 0.5.2?

Currently if you clone and build this repo, `0.5.0` gets used, which is unfortunate.

See also: https://github.com/Nilirad/bevy_prototype_lyon/issues/103

**Comment by mrk-its** [comment]
Just updated Cargo.lock, bevy_webgl2 points now to "0.5" rev
