### ISSUE TITLE
Use the cargo local-install tool for insuring the correct version of wasm-bindgen-cli

### ISSUE THREAD

**Issue by clinuxrulz** [mrk-its/bevy_webgl2_app_template#8]
wasm-bindgen-cli version needs to match the version of wasm-bindgen used by the bevy plugin for webgl, and that version may conflict with the version the user has installed.

If you get Makefile.toml to instead use the cargo local-install tool (for wasm-bindgen-cli only) then you can select the correct version of wasm-bindgen-cli to match the version bevy is using. See: https://crates.io/crates/cargo-local-install

The current version of wasm-bindgen-cli required is 0.2.69 for this template to work, and the latest version is currently 0.2.73.

**Comment by JulianRuiseco** [comment]
I just modified Makefile.toml as follows
```
[tasks.wasm-bindgen-cli]
install_crate = {crate_name = "wasm-bindgen-cli", version="0.2.69", binary = "wasm-bindgen", test_arg="--help"}
```

**Comment by clinuxrulz** [comment]
The end user might want their own version of wasm-bindgen-cli installed for their other projects. Might be better to do project-local install of the tool.

**Comment by thomasheartman** [comment]
@JulianRuiseco Thanks for the fix! I've been tearing my hair out trying to fix this error for a few weeks now (luckily only in my spare time), so making it work is an amazing feeling! 🎉 

@clinuxrulz  As for the project-local install, that sounds like a great idea! Do you happen to know how you might do that? I haven't heard about the tool before now, and am unsure whether it'd require changes in the cargo-make tool or just a config change.

**Comment by clinuxrulz** [comment]
@thomasheartman : Here is the tool https://crates.io/crates/cargo-local-install , its a command line utility for doing a local installs.

**Comment by thomasheartman** [comment]
> @thomasheartman : Here is the tool https://crates.io/crates/cargo-local-install , its a command line utility for doing a local installs.

Nice; thanks! Do you know whether it's easy to configure cargo-make to use `cargo local-install` instead of `cargo install` with the `install_crate` command? I tried looking through the docs, but couldn't find anything that looked like it would solve that 💁🏾
